# roles/kibana/tasks/main.yml
- name: Install Kibana
  apt:
    name: kibana-{{ kibana_version }}
    state: present
  when: "'ubuntu' in inventory_hostname"

- name: Install Kibana
  yum:
    name: kibana-{{ kibana_version }}
    state: present
  when: "'centos' in inventory_hostname"

- name: Start and enable Kibana service
  service:
    name: kibana
    state: started
    enabled: yes
